### ISSUE TITLE
Error using the plugin (Error: must have a callback)

### ISSUE THREAD

**Issue by olamy** [iandotkelly/gulp-license-finder#1] opened 2016-01-21 11:45 UTC
Hi,
I simply use:
var licenseFind = require('gulp-license-finder');

gulp.task('licenses', function() {
    return licenseFind()
        .pipe(gulp.dest('./audit'))
});

But I got this issue:

[22:44:05] Starting 'licenses'...
/Users/olamy/dev/sources/job/talend/data-prep/dataprep-webapp/node_modules/gulp-license-finder/node_modules/nlf/lib/formatters/standard.js:91
        throw new Error('must have a callback');
              ^
Error: must have a callback

**Comment by openhoat** [comment] 2016-02-15 10:39
Same problem for me.

It seems that the new version of nlf is not retro-compatible, try this fix that worked for me : add into package.json/devDependencies

```
"nlf": "1.3.2",
```

Olivier

**Comment by eskatos** [comment] 2016-03-21 21:03
Same problem here, thanks for the workaround.
+1 for a fix

**Comment by okolomiets** [comment] 2016-04-06 13:48
the problem is that options are not passed in formatter.render as 2nd argument

> formatter.render(data, function (err, output) { 

[see here](https://github.com/iandotkelly/gulp-license-finder/blob/master/index.js#L46)
The missing argument causes an exception in nlf module:

> function render(licenseData, options, callback) {
>     if (typeof callback !== 'function') {
>         throw new Error('must have a callback');
>     }

Just adding an empty object as options works fine for me.

**Comment by iandotkelly** [comment] 2017-05-06 19:38
Fixed in https://github.com/iandotkelly/gulp-license-finder/releases/tag/1.0.0 and https://www.npmjs.com/package/gulp-license-finder

**Closed as completed by iandotkelly** 2017-05-06 19:38 UTC
